name: "pbashyal-nmdp's Action in Action"
description: 'Greet with 42'
inputs:
  who-to-greet:  # id of input
    description: who to greet
    required: true
    default: 'World'
outputs:
  answer: # id of output
    description: 'The answer is always 42'
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
